### ISSUE TITLE
Research tech options

### ISSUE THREAD

**Issue by sbinlondon** [ReadWithAudrey/readwithaudrey#10]
Look into Airtable for database stuff and email automation, etc

Drop notes on your findings here

**Comment by BenNewman90** [comment]
Good explanation >> https://www.youtube.com/watch?v=7c4dCdIDSYY

- Creating a project with Airtable automatically makes an API to enable posting and getting data.
- npm install airtable.

**Comment by BenNewman90** [comment]
> @DenisKent @sbinlondon @BenNewman90 In case it's helpful I have put a doc called 'SL Scope - Audrey prototyping i' in a folder called developer notes in dropbox. The doc was prepared by an experienced developer and contains details about some of the tools he was thinking about using.
