### ISSUE TITLE
Meeting Friday, Oct 12

### ISSUE THREAD

**Issue by sbinlondon** [ReadWithAudrey/readwithaudrey#103]
Hi @Rob1Paul, I wanted to run a proposed change to our meeting time by you for tomorrow.

We've done our planning session this morning, taking stock of where we want to be by the end of the week. We would really like to do some user testing tomorrow and of course have something to hand over for you to user test at the weekend as well.

Would it be ok if you came in the afternoon instead of the morning so we're better able to reach these end-of-the-week goals? If you can come in around 3:30 or 4 pm, that would be ideal for us. Then we can regroup and walk you through where we've gotten to.

**Comment by Rob1Paul** [comment]
Hi @sbinlondon That's fine for me to come in in the afternoon. 
Would you mind if I made it a little earlier at say 2:30pm? Thanks, Rob

**Comment by sbinlondon** [comment]
@Rob1Paul We're going to need a bit of time post lunch (back at 2 pm) to collate our user test results. Is 3 pm a good compromise?
