### ISSUE TITLE
Design user testing questions

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#105]
We should use the framework provided in Design week

**Comment by matthall8** [comment]
## Observers Template

What is the Users name?

What are the User's top three pain points using application?

What is the Users profile?

Any Additional observations?

**Comment by matthall8** [comment]
@Rob1Paul - the site is now ready to be sent out for user testing. It is available on https://happy-mcnulty-44dd19.netlify.com and is best viewed on an iPhone 7/8.

Feel free to use the same template of questions we have used above. Please could you add all user feedback to issue #79 so we have all of the user feedback in the same issue?
