### ISSUE TITLE
Add final icon designs

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#109]
This may be provided by Rob

**Comment by matthall8** [comment]
@Rob1Paul - is it correct to assume you are happy with the homepage icon design? 

Rob made the following suggestions for the step process section:

![image](https://user-images.githubusercontent.com/9437789/46947295-48bd1300-d072-11e8-8afd-0d972521f472.png)

From: https://www.iconfinder.com/icons/1201899/distance_education_global_international_learning_icon

But seemed to be leaning more towards what we had already in the meeting. Any final thoughts on that section Rob?

**Comment by matthall8** [comment]
@Rob1Paul It's on here: https://www.flaticon.com/

**Comment by Rob1Paul** [comment]
thanks @matthall8 - I've put the three icons in the dropbox folder creative. I'm not 100% sold on them, but I think they're okay. Please can we change the colours in the icons so they match the colours we're using on the site e.g. change the icon green to our green. and perhaps change the join icon/ form to pink/red. etc. thanks.

**Comment by matthall8** [comment]
Thanks @Rob1Paul. I've made this part of the homepage updates issue.
