### ISSUE TITLE
Create a wireframe for the front-end

### ISSUE THREAD

**Issue by sbinlondon** [ReadWithAudrey/readwithaudrey#11]
- Use Figma and Envision
- Take inspiration from Rob's list of sites

**Comment by sbinlondon** [comment]
@Rob1Paul can you please link us to (or put in in the dropbox) your list of sites that you like taking design inspiration from?

**Comment by sbinlondon** [comment]
Rob's inspiration:

1. simple
2. minimalist
3. clean
4. clear

**Comment by Rob1Paul** [comment]
@sbinlondon in the dropbox I have created a folder called creative. In the folder there is a doc called 'Sources of Inspiration 01 Oct 2018'. Hopefully the links will provide a sense of the atmosphere / feel I'd like to try to create.

**Comment by sbinlondon** [comment]
@Rob1Paul Thanks! That was very helpful. One thing we've noticed is that the stock image you chose and the cards you like seem minimal, but also pop with fun and bright colours. It's very different to the current look. Does this mean you want to move more in the bright colours/fun direction, while keeping a clean feel?

I've attached a colour palette we pulled from the stock image. We're making some mock-ups based on this colour palette, keeping white as the dominant colour on the page for minimalism - does that seem like something you're going for?

<img width="660" alt="screen shot 2018-10-01 at 18 06 51" src="https://user-images.githubusercontent.com/37520401/46303996-53bd7100-c5a5-11e8-8c98-1497b3e9f9ef.png">

**Comment by Rob1Paul** [comment]
@sbinlondon Yes, I think you've distilled it neatly... a clean feel... with a shift towards brightness/ enjoyment. Happy to go with mock-ups based on this colour palette - keeping white as the dominant colour. By no means wedded to that image - in fact not sure about it? But probably a good idea to have a visual of some sort that represents what Audrey is about? Thank you.

**Comment by matthall8** [comment]
Hi @Rob1Paul - the link to the wireframes we went through yesterday is here:

https://www.figma.com/proto/B545gdhSeBmq1eyREceZOq6J/ReadingWithAudrey?node-id=27%3A0&scaling=min-zoom

![image](https://user-images.githubusercontent.com/9437789/46421077-4e892f00-c729-11e8-8626-562346ecde03.png)

This is the button you need to press to give you the same view we went through earlier today.

I've started to action your feedback from yesterday, let me know if there's anything further.

**Comment by matthall8** [comment]
@Rob1Paul's comments from issue #16:

It's occurred to me since we met that there may be one or two elements missing...

At the bottom they'll need to be 'Terms of Use' and 'Privacy'.
These aren't ready yet, but perhaps we can prepare for them/ placeholder?

I can't remember if we've already got a contact us button?

I don't recall if we had social media buttons - but I'm fairly sure I don't want them at this stage. It's another channel to manage.

**Comment by matthall8** [comment]
@Rob1Paul - Noted, I'll add Terms of Use, Privacy and Contact us. 

No social media buttons atm, agreed that is unnecessary this stage. We may add 'Share' buttons, but this will be through user's accounts and not be reliant on you managing a channel.

**Comment by matthall8** [comment]
Hi @Rob1Paul - based on your's and Stef's  feedback we have completed the greyscale Wireframes for the homepage and the questionnaire. Please see below. Let me know if you have any further feedback. We will continue the process of adding colour, with yesterday's feedback in mind.

## Homepage 

![image](https://user-images.githubusercontent.com/9437789/46484389-9a9fa680-c7f1-11e8-83d6-aab1610ff609.png)

## Questionnaire page - #1

![image](https://user-images.githubusercontent.com/9437789/46484633-0b46c300-c7f2-11e8-98c8-2fbc04491b9c.png)

## Questionnaire page  - #2

![image](https://user-images.githubusercontent.com/9437789/46484671-1c8fcf80-c7f2-11e8-8379-36044532cf38.png)

## Questionnaire page  - #3 

![image](https://user-images.githubusercontent.com/9437789/46484680-21ed1a00-c7f2-11e8-9af7-f2fdc8f90e70.png)

## Thank You Page
![image](https://user-images.githubusercontent.com/9437789/46485096-eacb3880-c7f2-11e8-9f04-b906891da3b9.png)

**Comment by Rob1Paul** [comment]
@matthall8 thanks for this Matt - are you able to give me a quick call? Thanks.

**Comment by matthall8** [comment]
@Rob1Paul - yes I can at 6pm if that works for you? Just in a talk atm.

**Comment by Rob1Paul** [comment]
@matthall8  yes, thanks.

**Comment by matthall8** [comment]
Running a little late @Rob1Paul. Will call you ASAP

**Comment by Rob1Paul** [comment]
@matthall8 lets leave it for now as I'm going to make my way home. if you're planning on working on it between now and when we see each other in the morning then it may be sensible to chat this evening (8:30 ish). Otherwise we can discuss in the morning. thanks

**Comment by matthall8** [comment]
Hi @Rob1Paul - thank you for your time earlier. I'm working my way through adding colour to the registration process pages but it's taking a bit longer than expected, I'll send it through tomorrow. 

In the meantime, please see below for the homepage we went through in case you want to share it for any further feedback

![image](https://user-images.githubusercontent.com/9437789/46547008-90011200-c8c2-11e8-8b4b-626dd277c093.png)

Have a great weekend!

**Comment by matthall8** [comment]
Hi @Rob1Paul,

I've added colour to the questionnaire pages, as per our discussion yesterday. There's still a little bit of work to do to make them pixel perfect but I wanted to share how the colours we chose yesterday look across the other pages.

![sign up - step 1 colour](https://user-images.githubusercontent.com/9437789/46569587-4a3e5b00-c94f-11e8-92f2-c6e98291e091.png)

![sign up - step 2 colour](https://user-images.githubusercontent.com/9437789/46569588-4a3e5b00-c94f-11e8-8312-5e14a331af32.png)

![sign up - step 3 colour](https://user-images.githubusercontent.com/9437789/46569589-4a3e5b00-c94f-11e8-97e1-44c66b0838f7.png)

![thank you - colour](https://user-images.githubusercontent.com/9437789/46569590-4a3e5b00-c94f-11e8-90e6-10b333328477.png)

Let me know your thoughts.

**Comment by matthall8** [comment]
Also set up the prototype in Figma to work with the colour version now - https://www.figma.com/proto/B545gdhSeBmq1eyREceZOq6J/ReadingWithAudrey?node-id=0%3A1&scaling=scale-down

**Comment by Rob1Paul** [comment]
thanks @matthall8 Is it possible to compare the pink/red we currently have with pink/red blouse here
https://www.penguinrandomhouse.com/books/549992/anne-franks-diary-the-graphic-adaptation-by-anne-frank/9781101871799/

you can download to get a high res image for matching. 

Interested to see the homepage side-by-side with the 'Read Aloud Together' with current pink/red and 
this pink/red in the blouse. 

thank you.

**Comment by Rob1Paul** [comment]
Hi @matthall8 Hi @sbinlondon  Hope you've having a good weekend. This is where I'm at with the homepage image main illustration. I like this illustration

https://www.shutterstock.com/image-vector/vector-set-hand-holding-books-icons-281774351

But I think one issue with it is that it may misrepresent the one-to-one nature of Audrey - because several hands are represented.... so people may think its group reading..

I also like this image from the same set...

https://www.shutterstock.com/image-vector/set-books-design-book-publishing-concept-314862134

I wondered if we could take out a couple of the pairs of hands and replace with books in the second image? @sbinlondon , I wasn't sure whether you had the photoshop skills to play around with this?

@matthall8 you'll notice that the background green and the pinky/red on some of the books/ arms is similar to the two colour combination we've gone for. 

In terms of icons for the how it works section .... I'm still having a think, but I'd like to convey a sense of a global community here... so along these sort of lines... for say the matching icon ...

https://www.shutterstock.com/image-vector/social-media-network-concept-human-hand-242560312

**Comment by sbinlondon** [comment]
@Rob1Paul I'm pretty confident I can combine the first two images if we get the hi res versions. I think those are a better representation of the feel we're going for than the last image you've linked to. 

The one issue with these illustrations as opposed to the one currently on the wireframes is that the new ones have the green background so they'd be a green square on a white background, or we'd need to make the background a matching green. Unless you want me to 'cut out' the hands and make the background white.

Love the colours and design y'all got to last week. I think it's really starting to look great!

**Comment by Rob1Paul** [comment]
@sbinlondon thanks! 

I'll purchase the two images and put them in the dropbox folder. Should I buy them as vector images?

I think it's a case of having a play around with what looks best... maybe the green background on the image will look good and we'll extend it/ use it for the whole background above the fold...  and use it as the green elsewhere... maybe it'll look best if we cut out the hands and books and have a white background.

**Comment by sbinlondon** [comment]
@Rob1Paul Yes please as SVGs if possible.

**Comment by Rob1Paul** [comment]
@sbinlondon i've put the two illustrations in the dropbox folder - creative. please let me know if they're okay... i'm not sure it was possible to get them as SVG

**Comment by sbinlondon** [comment]
![desktop splash page](https://user-images.githubusercontent.com/37520401/46615734-e1064580-cb10-11e8-90bf-e59868921feb.png)
![desktop signup page 1](https://user-images.githubusercontent.com/37520401/46615743-e6639000-cb10-11e8-8d5f-0e1771b85330.png)
![desktop thanks page](https://user-images.githubusercontent.com/37520401/46615746-e8c5ea00-cb10-11e8-87b8-4832d08638e0.png)

These are the desktop wireframes to give a general sense of how things would 'feel' on desktop as opposed to mobile (slightly different styles of the same components). Let us know if you have any feedback on these. 

I've got the vector images you put in Dropbox and I'm working with them a bit in photoshop. I'll post here when I have some stuff ready to look at, hopefully by the end of the day.

**Comment by Rob1Paul** [comment]
@sbinlondon Thanks very much for these... generally it's clean and simple with some warmth which is what we're aiming for. 
It's a little hard to tell exactly how they will look because you have the bottom and top green bands side by side.... it feels like the green bands are a bit overbearing/ dominant here.... compared to mobile. 
Thanks for your work on these.
