### ISSUE TITLE
Audrey - Accounts Access

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#13]
@matthall8 @BenNewman90 @DenisKent @sbinlondon Would you like me to provide access to the wordpress and hubspot accounts? Which of you should I provide this access for? Should I use the same emails you provided for the dropbox access? Thanks.

**Comment by DenisKent** [comment]
@Rob1Paul, yes please could you send it through to me, the same one as for the dropbox.

**Comment by Rob1Paul** [comment]
@DenisKent Done. You should receive an invitation from wordpress and hubspot. Let me know if they're not received shortly, and/or you need me to alter the permission settings. Also let me know if you need access to https://iwantmyname.com/ to access the readwithaudrey.com domain info.

**Comment by matthall8** [comment]
Thanks @Rob1Paul!
