### ISSUE TITLE
Update site content 

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#132]
Update the website content based on Rob's feedback

> Hi @matthall8 In the dropbox I have placed a latest version of the content for the website. The doc is called "Website copy 12th Oct 2018" (folder creative)
> 
> I'm not quite sure it's final! but it's fairly close.
> 
> In the doc you'll see all the copy for all the sections of the landing/homepage. Plus the copy for the About us page, which I'm now calling Why? and also the copy for the Contact Us page.
> 
> For the How it works section on the homepage (which I'm now calling 'Three steps to begin your reading adventure') i've picked out some icon suggestions - we can discuss these when we meet.
> 
> Regarding the FAQs (which I plan to call 'Questions' - these are v much a work in progress.... I've done a bit of brain dump and now they need rewording, ordering, categorising etc.. and I need to prepare the answers.
> 
> Privacy and Terms is something I'm going to leave til last to sort out.
> 
> Sorry I haven't followed your request re the tracked changes... although the sections are more or less the same, there was so much chopping and changing etc. that it became a bit confusing for me. Any changes going forward should hopefully be fairly small - and I will track these in the doc! :)
> 
> Thanks.

**Comment by matthall8** [comment]
Hi @Rob1Paul - I've just updated the content on the form 3 page and it is looking quite wordy on mobile:

![image](https://user-images.githubusercontent.com/9437789/47020166-a889eb80-d150-11e8-9712-dbcf7747a4e8.png)

Is there any way we can cut this down?

**Comment by Rob1Paul** [comment]
@matthall8 The FAQs called 'Questions' are now in the dropbox folder called creative. the doc is titled 'Questions 17th Oct 2018'. Thanks.
