### ISSUE TITLE
Brand Name

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#14]
@Rob1Paul - Should we use "Read with Audrey" or "Audrey" when referring to the service?

**Comment by Rob1Paul** [comment]
Good question! .... Welcome your views.... but I'm inclined towards 'Audrey'.

**Comment by matthall8** [comment]
@Rob1Paul We agree 👍. We'll use Audrey in text form and use iconography and imagery to demonstrate the 'Read with' part of the name.
