### ISSUE TITLE
Give Codecov access to repo

### ISSUE THREAD

**Issue by sbinlondon** [ReadWithAudrey/readwithaudrey#142]
Hi @Rob1Paul can you check your emails from Github? I'm trying log in to Codecov (a site that checks our testing coverage for code) and I can't add RwA to it because I'm not the owner of this repo. If you can grant access to that it would be great! No huge rush but it would be good to have by the end of the day. Thanks 😄

**Comment by Rob1Paul** [comment]
Hi @sbinlondon  sorry it's taken a while to do this. I have now approved access to Codecov.

**Comment by matthall8** [comment]
Thanks Rob.
