### ISSUE TITLE
Meeting Stef

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#15]
@matthall8 @BenNewman90 @DenisKent @sbinlondon Because I'm out of my depth on the tech side, I have a trusted friend/mentor (Stef) who's available to lend an ear and provide me with some advice/support on the tech/product. He's an experienced full stack developer who's very enthusiastic about the project. 

Would it be possible for him to meet with you all briefly this week to have a friendly and informal chat so that he can get a sense of how you're going about the project, what software tools you're thinking of using etc. 

From my perspective this would be useful as it helps to manage the project risk and provides some reassurance about areas I don't know a great deal about. 

Timings wise he could pop in tomorrow (Wed 3rd) afternoon at about 2pm (Wed 3rd), or Thursday (4th) in the morning at 10am. 

Thanks

**Comment by matthall8** [comment]
Hi @Rob1Paul, this sounds like a great idea. 2PM tomorrow works well for us - is Stef ok to come meet us here? Our FAC mentor, Izaak, will also join the meeting so that all tech stakeholders will be in the room.

**Comment by Rob1Paul** [comment]
@matthall8 @BenNewman90 @DenisKent @sbinlondon Thanks Matt. That's confirmed. Stef (Lewandowski) will come to you at Space4 tomorrow at 2pm.
