### ISSUE TITLE
Sign Up / Questionnaire Fields 

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#16]
**_Basic Details_**

First Name
Surname
Gender
Email
Age
Country & Timezone
Reader or Listener (likely move to reading preferences once we begin to capture this data)

**_Reading Preferences_** (Long term, do we need to capture this initially?)

Abridged or not
Short story / excerpt or full length
Fiction / non fiction
Chose or recommend
Length of reading

**_Your Bio_** 

Bio
Any special requests

**Comment by matthall8** [comment]
@Rob1Paul - this is the questionnaire information we discussed earlier.

**Comment by Rob1Paul** [comment]
Hi @matthall8 Here are the (final!) profile questionnaire fields, in the order I think is best, and divided into sections ...

______________

Basic Details (i)

1.	First Name
2.	Surname
3.	Email
______________

Basic Details (ii)

4.	Gender
5.	Age
6.	City, Country & Timezone
______________

Reading preferences

7.	Reader or Listener or Both
8.	Reading material
______________

About you

9.	Bio
10.	Special requests
______________

Out of curiosity....

11.	Attitude to Abridgement
_____________

I assume you don't need me to finalise the exact wording just yet?

Draft wording for the new questions (8) and (11) below... you'll see they're both closed questions (one is ranking, the other an attitude scale). 

(8) What would you like to read with your reading partner? 
Please rank the option below in order - favourite 1st. 

1.	Several fantastic short stories
2.	A wonderful novella (short novel)
3.	A fascinating work of non-fiction 


(11) How do feel about reading an abridged book? 
(That’s a shortened version of the original book, condensed into fewer words, but it still retains a sense of the original book and the main plot is preserved). It’s a topic that can divide opinion!

              1              2               3              4             5
Don’t mind at all                                        Really don’t like the idea 

I'll finalise what I think are all the necessary fields for the Airtable tomorrow. 

Thanks for all your help.

**Comment by matthall8** [comment]
Thanks for this @Rob1Paul. We agree with the questions but we have some concerns over 5 sections being too many for only 11 questions, leading to a poor user experience and increasing the drop out rate.

We recommend a 3 section process:

___

Step 1. Basic Info 

First Name
Surname
Email

___

Step 2. Further Info

Gender
Age
City, Country & Timezone
Reader or Listener or Both
Reading material
Attitude to abridgement 

____ 

Step 3. About you

Bio
Special requests

____

Let me know your thoughts.

**Comment by Rob1Paul** [comment]
@matthall8 Thanks for your feedback. I am happy to consolidate into 3 steps (or perhaps 3 and a half!). 

I would like the 'Attitude to abridgement' question to be the final question... 
almost as if it's an after thought/ research question.... kind of like.... 

oh, one last thing 'How do feel about reading an abridged book?'

I would place this 'subtly' after 'special requests'

**Comment by matthall8** [comment]
Ok great thanks @Rob1Paul.

We'll do it in this order:

___

Step 1. Basic Info

First Name
Surname
Email

___

Step 2. Further Info

Gender
Age
City, Country & Timezone
Reader or Listener or Both
Reading material

___

Step 3. About you

Bio
Special requests

And then Attitude to abridgement will either be the final question of step 3, or step 3.5 if we can find a good way to do it subtly.

**Comment by Rob1Paul** [comment]
@matthall8 Thanks. Number of questions, order of questions, number of sections, all agreed. 
Actual wording TBC. 
Please let me know when you'd like this. 

Do we need to decide now which fields are compulsory to complete? 
Possibly all. Maybe not surname?

**Comment by matthall8** [comment]
@Rob1Paul. First draft of wording will come across as part of the wider first draft content - possibly tomorrow.
