### ISSUE TITLE
Transactional Emails - Copy

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#168]
@matthall8 @DenisKent The copy for the various transactional emails is in the dropbox folder 'creative. The doc is titled 'Transactional Email Templates 18th Oct 2018'.
We haven't yet agreed the time settings for when each should be sent.

**Comment by matthall8** [comment]
Thanks Rob. We'll drop it in.

Our thoughts are:

- Welcome email - straight after successful registration  
- Pairing email - Within an hour of you pairing two people up
- Reminder email - 24 hours after lead captured 
- Feedback form - 8 days after pairing.

**Comment by Rob1Paul** [comment]
@matthall8 Agree.  

Thought... 8 days is quite a long-time... I wonder if we should insert another transactional email 'gentle reminder to contact your reading partner' say 48hrs after the pairing email. 

If simple to add into the workflow I think this is a good idea. If not, no worries.

**Comment by matthall8** [comment]
@Rob1Paul Great. It'd be quite difficult for us to add another email at this stage so let's leave it for now and we can discuss later.

**Comment by matthall8** [comment]
Copy has been added. We'll leave you to update the design Rob.
