### ISSUE TITLE
Alternatives to dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#187]
> I know I am spotting this quite late. But surely there is a better way of putting the content in there through CMS?
> Any ideas of alternatives?
> It is all over our project:

@DenisKent made this comment Ben. Any thoughts based on your research whilst doing the MD stuff?

**Comment by BenNewman90** [comment]
That was how it was done in the example project from NetlifyCMS.
