### ISSUE TITLE
Airtable fields

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#19]
Hi @BenNewman90 @DenisKent I am working on the Airtable fields today with a view to getting info over to you later this afternoon/ this evening. It would be helpful to have sight of the Airtable you showed me yesterday so I can organise my thoughts. Can you share? I have an Airtable account with the email readwithaudrey@gmail.com 
Thanks

**Comment by DenisKent** [comment]
@Rob1Paul, Thanks for being so quick with the fields. I've sent the invite via email.

**Comment by Rob1Paul** [comment]
Hi @BenNewman90 Hi @DenisKent Hope you've had a good day. I have added a spreadsheet called 'Fields for Airtable 04 10 2018' to the shared dropbox (folder 'tracking') so we can discuss tomorrow. Have a good evening.
