### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#197]
![image](https://user-images.githubusercontent.com/28222381/47234076-88666080-d3cc-11e8-9265-7e17817b5d25.png)

When you mess with the lead there can be an error on form 3 submission

Looking for pair = true by default

Looking for pair should be false when pairs are matched

pairing status default as active

Finalise Schema

Outbox for gmail or sendgrid.. check what emails have been sent

Is sending attachments a definite requirement?

**Comment by matthall8** [comment]
Included in separate issues.
