### ISSUE TITLE
Review and update copy section in transactional email

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#204]
Review and update copy section in transactional email ‘reader and listener allocation’ please can you send me the two versions of copy you are proposing? (Matt, think you deleted original text from dropbox doc.)

**Comment by matthall8** [comment]
Added all content on my Mac to Box

@DenisKent - please can you send through the two versions to Rob?

**Comment by DenisKent** [comment]
@Rob1Paul Sorry for the delay here is the text, and below is the logic.

You’ve both said you’d be happy to read and listen. Therefore we suggest ${user1_name} kicks off as the reader for your first chapter. Then perhaps you can take turns as the reader and listener alternating between chapters? If this doesn’t feel quite right, please have a chat and choose an arrangement you’re both comfortable with.

Can I suggest ${reads} begins as the reader for the first chapter and see how it goes from there? But please choose an arrangement you’re both comfortable with.

``` javascript
  let reads = user1_name;
  if (reader === 'user2') {
    reads = user2_name;
  } else if (reader === 'both') {
    return `You’ve both said you’d be happy to read and listen. Therefore we suggest ${user1_name} kicks off as the reader for your first chapter. Then perhaps you can take turns as the reader and listener alternating between chapters? If this doesn’t feel quite right, please have a chat and choose an arrangement you’re both comfortable with.`;
  }
  return `Can I suggest ${reads} begins as the reader for the first chapter and see how it goes from there? But please choose an arrangement you’re both comfortable with.`;
```
