### ISSUE TITLE
Polish homepage and make sure it renders across all devices and browsers

### ISSUE THREAD

**Issue by BenNewman90** [ReadWithAudrey/readwithaudrey#257]
- [x] Review layout/positioning of text and images above the fold when landing on the homepage. Creat a little more space between text and images. Explore separate images and/or increase the opacity of images
- [x] More padding to the right of 'get started' at the top right-hand corner of the page
- [x] 'Let's find you a reading partner' - moved from above to just below the get started button
- [x] Reinstate second section: What is Audrey? Who is it for? Who do I read with?
- [x] Small arrows between join, read and connect in one of the brand colours.

**Comment by BenNewman90** [comment]
@Rob1Paul, I've added in the arrows. Have a look and see what you think.

**Comment by Rob1Paul** [comment]
Hi @BenNewman90 ,

Thanks for your work on the Audrey website. Once you've had a quick look at my comments below lets have a quick chat. 

Browser compatibility. Comments noted about Internet Explorer. 

Agree with your recommendation re green arrow - simple is better - lets remove them for now. 

Incomplete - Hand hovers accurately/correctly over all homepage ‘get started' buttons. There are places all around some of these buttons where the hand appears. 

![image](https://user-images.githubusercontent.com/43749507/48343071-4b0e8f00-e669-11e8-95a3-fa3c24332f96.png)

![image](https://user-images.githubusercontent.com/43749507/48343109-6e393e80-e669-11e8-97fe-7c254fd4d365.png)

![image](https://user-images.githubusercontent.com/43749507/48343298-ebfd4a00-e669-11e8-84b0-e0ce0f93b174.png)


'Let's find you a reading partner' - moved from above to just below the get started button.
On some browsers/ small devices e.g. tablet/ laptops these words appear on top of the books image. 
I'd prefer this didn't happen.

**Comment by Rob1Paul** [comment]
@BenNewman90 
@BenNewman90 

In the CMS I am trying to update the thank you for contacting us page...
I am trying to change the header to read...
'Thank you for contacting us!'
and then deleting this from the main text. 
but the cms is not allowing me to do this. 

![image](https://user-images.githubusercontent.com/43749507/48345909-49e16000-e671-11e8-83f7-dc7d5f2fb89b.png)


If you sign up with an email that already exists the following text appears

'Sorry, a user with that e-mail address already exists, please chose another e-mail or check your inbox'

This needs updating to:

'Sorry, a user with that e-mail address already exists, please cho**o**se another e-mail or check your inbox**.**'

**Comment by Rob1Paul** [comment]
@BenNewman90 

![image](https://user-images.githubusercontent.com/43749507/48349067-0db2fd00-e67b-11e8-88cc-447eb276f0f6.png)
