### ISSUE TITLE
Email address location for Contact us form

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#271]
- [x] Confirm and set up so contact form submissions on website go to readwithaudrey@gmail.com

**Comment by BenNewman90** [comment]
![image](https://user-images.githubusercontent.com/24710103/48411295-110cbe00-e739-11e8-82f9-329f2d82f4ea.png)

**Comment by BenNewman90** [comment]
![image](https://user-images.githubusercontent.com/24710103/48411377-4fa27880-e739-11e8-907e-b9c9ce4573e1.png)

**Comment by BenNewman90** [comment]
![image](https://user-images.githubusercontent.com/24710103/48411423-6a74ed00-e739-11e8-8ad4-a5e8190bcf64.png)

**Comment by BenNewman90** [comment]
@Rob1Paul is this a satisfactory solution for you? 

The choice is between this or having your email address on the site. It is definitely more professional have a form rather than an email address. 

The free version has a maximum of 100 form submissions a month. The $45 upgrade gives you up to 1000.

**Comment by Rob1Paul** [comment]
@BenNewman90 Yes, this is fine. Although I'm not sure you would need to upgrade to Team Pro @ $45 per month. Instead I think the free plan provides access to 'per-site addons' which includes Forms Pro @ $19 which gets you up to 1000 submissions. But all someway off!

![image](https://user-images.githubusercontent.com/43749507/48435696-04a65680-e775-11e8-9d7e-41a878fee3bd.png)

**Comment by BenNewman90** [comment]
@Rob1Paul Okay great. I'll close the issue.
