### ISSUE TITLE
SendGrid

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#272]
- [x] Ensure verifiable proof of sending for all automated transactional emails i.e. these emails are visible in the Gmail outbox. 

- [x] Change email address being used for transactional emails to readwithaudrey@gmail.com and update in send grid. 

- [x] Update transactional email headers as per dropbox file

- [x] Sendgrid unsubscribe set-up
 
- [x] For the transactional email lead_reminder, the first name is not set up to capture from airtable.

- [x] Have the Date() added to the table rather than a tick when an email is sent.

**Comment by BenNewman90** [comment]
@Rob1Paul, for the transactional email timing I've set the lead email to 24 hours after the lead creation date, and the feedback email is sent 8 days after the pairing date. Let me know if you would like this changed.

**Comment by BenNewman90** [comment]
@Rob1Paul, regarding the unsubscribe links, I do not believe we need them for transactional emails. Read this article: https://www.quora.com/What-are-the-rules-around-transactional-emails-If-I-send-notification-emails-do-they-need-unsubscribe-links.

I suggest we remove this requirement.

**Comment by BenNewman90** [comment]
@Rob1Paul, this is far more informative: https://termsfeed.com/blog/gdpr-transactional-emails/.

In summary, transactional emails do not typically include an unsubscribe option.
