### ISSUE TITLE
Heroku paid plan

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#273]
- [ ] Shift to heroku paid plan
- [ ] Research if Heroku paid plan can have more than one server

**Comment by BenNewman90** [comment]
@Rob1Paul, it could be a good time to do this.

**Comment by Rob1Paul** [comment]
@BenNewman90 How does Heroku billing work? Is it based on usage/ traffic? If there is a big spike in traffic usage - is there a risk that I will suddenly incur a large bill? Feel free to call if easier to explain over the phone. Thanks

**Comment by Rob1Paul** [comment]
@BenNewman90 I've added a credit c on heroku.
Not clear if the hobby $7 per dyno/month plan  will cover both what you're doing i.e. website, and what stef is doing as well, i.e. the prototoype.....
or do I have to pay separately for each?

**Comment by BenNewman90** [comment]
@Rob1Paul , you will have to pay for both. I have activate the happymcnaulty site, however it can easily be deactivated if you change your mind. I will close this issue for now.
