### ISSUE TITLE
SendGrid - Feedback email

### ISSUE THREAD

**Issue by BenNewman90** [ReadWithAudrey/readwithaudrey#300]
- [ ] Does not currently BCC in readwithaudrey.data@gmail.com
- [x] Set feedback email to be sent 8 days after pairing

**Comment by Rob1Paul** [comment]
@BenNewman90 I've just introduced a first 'real pair' through airtable. Therefore we should adjust the feedback email so they receive it after **7** days - otherwise they'll receive it today.
