### ISSUE TITLE
Design feedback from Rob

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#31]
* Like the simplicity

* Don’t like the shadow on titles

* Like the orange title colours

* Unsure about the blue, something brighter

* Don’t know about the image on the first page

* Like the simplicity of the header

* Maybe use the green in the book

* Can the book icon convey more about the project, two people with a book

* "Join us" in the header instead of sign up now

* 1,2,3 step sub-titles could use some colours

* remove learn more on p1

* lose outline on signup now buttons

**Comment by matthall8** [comment]
All of this feedback has been implemented in the Wireframes #11.
