### ISSUE TITLE
Airtable - click confirm_pairing doesn't send pairing email

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#327]
Hi @BenNewman90 not sure what I'm doing wrong or if there is a glitch. 
Not showing pairing_email_sent
See pairing id 51

**Comment by BenNewman90** [comment]
@Rob1Paul, I've set up a 'cronjob' on cron-job.org to poke the Heroku server every fifteen minutes. It now should not go to sleep as the cronjob is tricking Heroku into thinking it's being used.
