### ISSUE TITLE
Add Analytics to ReadWithAudrey website

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#328]
@BenNewman90 Before we make the site live, it would be helpful to have some basic analytics so I have a sense of visitor numbers, conversions etc... I'm guessing the starting point/ simplest option here is Google Analytics?

**Comment by BenNewman90** [comment]
@Rob1Paul, Google Analytics is setup. Log in to Google Analytics with readwithaudrey.data@gmail.com. 
![image](https://user-images.githubusercontent.com/24710103/49049163-c2016700-f1d5-11e8-8647-2be5a809cfd4.png)

**Comment by Rob1Paul** [comment]
Thanks @BenNewman90
