### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#33]
@matthall8 @sbinlondon @DenisKent @BenNewman90 Just wanted to say a BIG thank you for all efforts and hard work on Audrey this week. I have really enjoyed working on this with you. Hope you all have a good weekend, Rob

**Comment by DenisKent** [comment]
Thanks @Rob1Paul, it has also been a pleasure on our side.
We have just been asked if we would like to present the final project at a tech-for-better launch party on Thursday 25th of October. Would you be interested in joining or doing some of the presenting?

**Comment by matthall8** [comment]
Echo @DenisKent's comments - have a great weekend Rob!

**Comment by sbinlondon** [comment]
Thanks @Rob1Paul that's really kind of you!

**Comment by DenisKent** [comment]
@Rob1Paul, It looks like the party/presentation will be postponed until a later date. I'll let you know if I hear any more.
