### ISSUE TITLE
User Journey - Sign up as an ambassador or content creator

### ISSUE THREAD

**Issue by BenNewman90** [ReadWithAudrey/readwithaudrey#340]
- [ ] Link at in footer takes you to a signup form

- [ ] Copy at the top explains the two roles (ambassador and content creator) - add to content management system.

- [ ] Form has a drop down to choose which role (ambassador and content creator)

- [ ] name, email address, name of organisation (leave blank if not applicable), optional message

- [ ] Signups add the new 'partner' to their respective tables.

- [ ] Add an automated email saying 'thanks for registering interest in getting involved. Someone from the team with get in contact with you soon.'

**Comment by BenNewman90** [comment]
@Rob1Paul , I'm closing this issue for now. If you want to make any comments on this issue it can be reopened at a later date.

**Comment by Rob1Paul** [comment]
@BenNewman90 That's sensible. I pushed ahead too quickly with this. I've decided to pause it for now. Thanks
