### ISSUE TITLE
Join with an Org - Front end. Create option in Form 1

### ISSUE THREAD

**Issue by BenNewman90** [ReadWithAudrey/readwithaudrey#341]
- [x] Create an option in Form 1 for choosing an organisation: "Are you joining as part of an organisation" - Yes or no option, followed by manually typing in the code associated with the organisation. 
- [x] Error message not code does not match an active partner organisation
- [x] Expandable answer/question like Form 3 explaining how the partner organisation system works
- [ ] Review which questions are marked as 'required', so that members of organisations are not forced to answer irrelevant questions.

**Comment by Rob1Paul** [comment]
@BenNewman90 

I don't think you've given me access to the 'Audrey Database - Staging' Airtable so I can't see how the website form and airtable listen/speak to one another. 

I tried to enter some dummy data into Form 1 including the codes you suggested. However when I clicked continue nothing happened. 

![image](https://user-images.githubusercontent.com/43749507/50341515-ef141180-0516-11e9-8bd9-ae68357d13d9.png)

Happy to have another try when you're ready - I'll go quiet from about 3pm today.
