### ISSUE TITLE
Netlify - CMS - link not working?

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#374]
Hi @BenNewman90 The link to the content management system does not seem to be working ... https://happy-mcnulty-44dd19.netlify.com/admin

**Comment by BenNewman90** [comment]
Hi Rob,

Go to https://readwithaudrey.com/admin <https://readwithaudrey.com/admin>.

Thanks,

Ben

**Comment by Rob1Paul** [comment]
That was quick - Thank you :)
