### ISSUE TITLE
Form 3 submit button is unreliable/ not working

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#377]
@BenNewman90 The form3 submit button is being unreliable/ not always working. please could you take a look... 

See image below. Thanks...

![image](https://user-images.githubusercontent.com/43749507/51246350-2d6be780-1982-11e9-99c9-60077c06a42e.png)

**Comment by BenNewman90** [comment]
Hi Rob,


I’m unsure what caused the error.

I have set up basic error monitoring so I will be able to see what’s wrong next time it happens. If you are able to replicate the error, please do.

Thanks,

Ben

**Comment by BenNewman90** [comment]
I notice that you were making changes to the site with the CMS, which updates the master. This triggers a ‘rebuild’ on Heroku, which take a few seconds or minutes. It’s possible you were trying to sign up during the rebuild.

**Comment by Rob1Paul** [comment]
@BenNewman90 I think the error occurs where you click on the submit button more than once in close succession. I just tried this by clicking three or four times on submit... i saw a quick glance of the error message appear before it took me to the thank you page. 

in airtable my sign up appears four times.

i seem to think this is a longstanding problem we've had to do with this form three submit button and the short, and slightly unusual pause that occurs once its clicked

**Comment by BenNewman90** [comment]
Hi Rob,

Yes, this is a familiar problem. I can resolve this if you like, though I am busy today and likely tomorrow. 

Thanks,

Ben

**Comment by Rob1Paul** [comment]
@BenNewman90 Do you know what the actual problem is and how to resolve it? 
I thought it had been resolved before.
I was just about to send a mailshot to some old users, and just wanted to double check everything was working. I'm hesitant to send... it would be frustrating for people if they spend time writing a nice bio and then it doesn't send properly/ is lost.

**Comment by BenNewman90** [comment]
The issue #323 refers to this and is still outstanding on Github (though it’s not written completely clearly), so has not yet been attended to. 

I know what the issue is, it’s that the buttons need a cool down period (of a sec or so) to allow the Airtables to update before another request is sent (i.e. by clicking submit again).

I will look at it this evening.

**Comment by Rob1Paul** [comment]
@BenNewman90 Just got this server error...

![image](https://user-images.githubusercontent.com/43749507/51379466-62ee0d80-1b07-11e9-9b4d-483f2e62c08d.png)

**Comment by Rob1Paul** [comment]
@BenNewman90 however the form does post to airtable and i receive the welcome  email.

**Comment by BenNewman90** [comment]
@Rob1Paul , was this when you signed up with rob@readwithaudrey.com?

**Comment by Rob1Paul** [comment]
@BenNewman90  yes i think it was

**Comment by BenNewman90** [comment]
@Rob1Paul . SendGrid does not like you signing up with the same email address which it sends from. rob@readwithaudrey is bcc'd in to all emails, which seems to be cause confusion.

**Comment by BenNewman90** [comment]
@Rob1Paul this issue is now resolved. I will now look at the display issue.
