### ISSUE TITLE
Airtable - Pairing not working

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#379]
@BenNewman90 I have just tried to do a pairing but it is not working for some reason.

**Comment by BenNewman90** [comment]
Hi Rob,

I believe the error resulted from you using rob@readwithaudrey.com <mailto:rob@readwithaudrey.com> as one of he users. That is the email that is used by Sendgrid.

I just signed up and changed the pairing and it worked. 

Thanks,

Ben

**Comment by BenNewman90** [comment]
@Rob1Paul ,

I'm going to close this issue as as long as you don't sign up with that email address everything is fine.

Thanks,

Ben
