### ISSUE TITLE
Feedback on landing page + UI

### ISSUE THREAD

**Issue by stefl** [ReadWithAudrey/readwithaudrey#85]
Hi folks,

It looks like you're nearly at a good point for me to give some feedback on progress?

So far it looks like the areas you might need me to look at for front end feedback are:

* Typography
* Landing page content
* Landing page structure
* UI components
* Responsive / cross-browser support
* Accessibility
* Page speed
* User flow for sign up

Anything else that you'd like me to take a look at?

Stef

**Comment by matthall8** [comment]
Hi @stefl ,

This seems like a comprehensive list - it'd be great to get any thoughts on the imagery/icons too. We should be in the position for the site to be reviewed on mobile by the end of today dependent on any feedback from Rob #65. I'll update this issue once we are ready.

The desktop version of the website will take a little bit longer, I'll let you know when that is ready to be reviewed.

**Comment by matthall8** [comment]
Hi @stefl - The site is now ready for your feedback. It is available on https://happy-mcnulty-44dd19.netlify.com and is best viewed on an iPhone 7/8.

All pages except TOC/Privacy work. The form doesn't capture data yet but clicking the continue button, and the submit button on the final page, will take you all the way through to the Thank You page.

Let me know if you need anything further.

**Comment by stefl** [comment]
@matthall8 thanks - I'll take a look and give feedback for you. 👍
