### ISSUE TITLE
Change email provider from Mailgun to sendGrid

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#98]
Mandril has template functionality which would enable Rob to edit emails sent out

**Comment by DenisKent** [comment]
@Rob1Paul , it is looking like SendGrid should be fine for both transaction and marketing activities. So no need for MailChimp or Mandrill. 
For SendGrid I believe it is possible to get the marketing activities working with our I've been back-end. I'll let you know if there are any problems early next week.

**Comment by Rob1Paul** [comment]
Thanks @DenisKent Before we make a final decision on this I think it's probably worth getting a view from @stefl . He may have an opinion on the merits of one over the other, and which one to opt for, so his input would be helpful on this.

**Comment by stefl** [comment]
Does Sendgrid enable Rob to edit the templates without having to edit code in this git repo? I thought it just did the email delivery component.

Mandrill gives you a UI that lets you make changes without having to know how to write or commit code.

**Comment by DenisKent** [comment]
@stefl, yep it has the exact same functionality to edit templates. Looks almost identical to the mailChimp one. That's why we changed from Mailgun

**Comment by DenisKent** [comment]
Guide on sendgrid api: https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send
https://sendgrid.com/docs/API_Reference/api_v3.html

**Comment by matthall8** [comment]
Completed as per #165.
